import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Providers } from "@/components/providers";
import { Header } from "@/components/header";
import { auth } from "@/auth";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="ja" suppressHydrationWarning>
      <body
        className={[
          geistSans.variable,
          geistMono.variable,
          // ▼ 全ページ共通の基底スタイル
          "min-h-screen bg-background text-foreground antialiased",
        ].join(" ")}
      >
        <ThemeProvider
          attribute="class" // <html class="dark"> を自動制御
          defaultTheme="system" // "system" → OS設定を初期値にする、"light" → ライトモードが初期値になる
          enableSystem
        >
          <Providers session={session}>
            <Header />
            <main className="container mx-auto px-4 sm:px-6 lg:px-8 py-6">
              <div
                className="pointer-events-none absolute -left-24 -top-24 h-80 w-80 rounded-full blur-3xl opacity-30
                bg-gradient-to-tr from-indigo-400 to-fuchsia-400 dark:from-indigo-600 dark:to-fuchsia-600"
              />
              <div
                className="pointer-events-none absolute -right-24 -bottom-24 h-80 w-80 rounded-full blur-3xl opacity-20
                bg-gradient-to-tr from-cyan-400 to-emerald-400 dark:from-cyan-600 dark:to-emerald-600"
              />
              <div className="relative z-10">{children}</div>
            </main>
          </Providers>
          <Toaster position="top-center" richColors />
          {/* 共通フッターを入れるならここ */}
        </ThemeProvider>
      </body>
    </html>
  );
}
